// Generated by tools/build-standalone.cjs from src ES modules.
// Do not edit by hand; edit the modules and rerun the builder.
(() => {
"use strict";

// format.js
const numberFormatter = new Intl.NumberFormat("en-US", {
  maximumFractionDigits: 2,
});

const currencyRateFormatter = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  maximumFractionDigits: 5,
});

function asNumber(value, fallback = 0) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function addMonths(date, monthOffset) {
  const target = new Date(date.getFullYear(), date.getMonth() + monthOffset, 1);
  const lastDay = new Date(target.getFullYear(), target.getMonth() + 1, 0).getDate();
  target.setDate(Math.min(date.getDate(), lastDay));
  return target;
}

function parseStartDate(state, defaults) {
  const [year, month, day] = String(state.startDate || defaults.startDate).split("-").map(Number);
  if (!year || !month || !day) {
    const [defaultYear, defaultMonth, defaultDay] = defaults.startDate.split("-").map(Number);
    return new Date(defaultYear, defaultMonth - 1, defaultDay);
  }
  return new Date(year, month - 1, day);
}

function monthDate(state, defaults, index) {
  return addMonths(parseStartDate(state, defaults), index + 1);
}

function monthLabel(state, defaults, index, style = "short") {
  return monthDate(state, defaults, index).toLocaleDateString("en-US", {
    month: style,
    year: "numeric",
  });
}

function exactDateLabel(date) {
  return date.toLocaleDateString("en-US", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function vestingDateLabel(state, defaults, monthIndex) {
  return exactDateLabel(addMonths(parseStartDate(state, defaults), monthIndex + 1));
}

function formatterFor(compact = false) {
  return new Intl.NumberFormat("en-US", {
    notation: compact ? "compact" : "standard",
    maximumFractionDigits: compact ? 1 : 0,
  });
}

function money(state, value, currency = state.reportCurrency) {
  const prefix = currency === "SGD" ? "S$" : "$";
  return `${prefix}${formatterFor().format(Math.round(value || 0))}`;
}

function compactMoney(state, value, currency = state.reportCurrency) {
  const prefix = currency === "SGD" ? "S$" : "$";
  return `${prefix}${formatterFor(true).format(Math.round(value || 0))}`;
}

function monthOptions() {
  return Array.from({ length: 12 }, (_, index) => [
    index + 1,
    new Date(2026, index, 1).toLocaleDateString("en-US", { month: "long" }),
  ]);
}

function safeFileName(value, suffix) {
  const base = String(value || "projection")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return `${base || "projection"}${suffix}`;
}

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}


// state.js
const DEFAULTS = {
  scenarioName: "Sample Compensation Projection",
  startDate: new Date().toISOString().slice(0, 10),
  years: 4,
  cashCurrency: "SGD",
  equityCurrency: "USD",
  reportCurrency: "SGD",
  usdToSgd: 1.35,
  overviewCashflowView: "monthly",
  overviewCashflowCumulative: false,
  cashflowZoom: 1,
  cashflowWindowStart: 0,
  cashflowWindowEnd: 0,
  equityWindowStart: 0,
  equityWindowEnd: 0,
  selectedEquityPoint: null,
  cashflowComponents: {
    salary: true,
    bonus: true,
    signOn: true,
    equityValue: true,
  },
  detailCashflowView: "monthly",
  detailCashflowCumulative: false,
  mixPeriod: "all",
  baseSalary: 120000,
  salaryBasis: "annual",
  salaryGrowth: 3,
  bonusPercent: 10,
  bonusMonth: 3,
  signOnYear1: 10000,
  signOnYear1Mode: "lump",
  signOnYear2: 0,
  signOnYear2Mode: "monthly",
  rsuGrantValue: 100000,
  startingSharePrice: 100,
  annualEquityGrowth: 5,
  vestingYears: 4,
  vestingCadence: "custom",
  customVestingMode: "weights",
  customVestingPattern: "25:25:25:25",
  customVestingSpread: "quarterly",
  cliffMonths: 0,
};

function loadState(storage = localStorage) {
  try {
    const saved = JSON.parse(storage.getItem("compProjectionState"));
    const merged = { ...DEFAULTS, ...saved };
    merged.cashflowComponents = {
      ...DEFAULTS.cashflowComponents,
      ...(saved?.cashflowComponents || {}),
    };
    if (!saved?.startDate && saved?.startMonth) {
      merged.startDate = `${saved.startMonth}-01`;
    }
    return merged;
  } catch {
    return { ...DEFAULTS, cashflowComponents: { ...DEFAULTS.cashflowComponents } };
  }
}

function persistState(state, storage = localStorage) {
  storage.setItem("compProjectionState", JSON.stringify(state));
}


// model.js
const scenarioGrowthRates = [-15, -10, 0, 5, 10, 15, 25];

const cashflowComponentMeta = [
  { key: "salary", label: "Salary", className: "salary-fill" },
  { key: "bonus", label: "Bonus", className: "bonus-fill" },
  { key: "signOn", label: "Sign-on", className: "signon-fill" },
  { key: "equityValue", label: "Equity", className: "equity-fill" },
];

function annualSalaryForYear(state, yearIndex) {
  const startingAnnualSalary = state.salaryBasis === "monthly" ? state.baseSalary * 12 : state.baseSalary;
  return startingAnnualSalary * (1 + state.salaryGrowth / 100) ** yearIndex;
}

function convertCurrency(state, value, fromCurrency, toCurrency = state.reportCurrency) {
  if (fromCurrency === toCurrency) return value;
  const usdToSgd = Math.max(0.0001, asNumber(state.usdToSgd, 1.35));
  if (fromCurrency === "USD" && toCurrency === "SGD") return value * usdToSgd;
  if (fromCurrency === "SGD" && toCurrency === "USD") return value / usdToSgd;
  return value;
}

function signOnForMonth(state, monthIndex) {
  const buckets = [
    { start: 0, amount: state.signOnYear1, mode: state.signOnYear1Mode },
    { start: 12, amount: state.signOnYear2, mode: state.signOnYear2Mode },
  ];
  return buckets.reduce((sum, item) => {
    if (monthIndex < item.start || monthIndex >= item.start + 12) return sum;
    if (item.mode === "monthly") return sum + item.amount / 12;
    return sum + (monthIndex === item.start ? item.amount : 0);
  }, 0);
}

function vestingInterval(state) {
  if (state.vestingCadence === "monthly") return 1;
  if (state.vestingCadence === "quarterly") return 3;
  if (state.vestingCadence === "annual") return 12;
  if (state.customVestingSpread === "monthly") return 1;
  if (state.customVestingSpread === "quarterly") return 3;
  return 12;
}

function customVestingWeights(state) {
  const values = String(state.customVestingPattern || "")
    .split(/[:;,]/)
    .map((value) => asNumber(value.trim(), NaN))
    .filter((value) => Number.isFinite(value) && value >= 0);
  return values.length ? values : [100];
}

function customVestingEvents(state) {
  if (state.customVestingMode !== "events") return [];
  return String(state.customVestingPattern || "")
    .split(/[,\n]+/)
    .map((entry) => {
      const [monthPart, sharesPart] = entry.trim().split(/[:=/\s]+/);
      return { month: Math.round(asNumber(monthPart, 0)), shares: asNumber(sharesPart, 0) };
    })
    .filter((event) => event.month >= 0 && event.shares > 0)
    .sort((a, b) => a.month - b.month);
}

function vestingSharesForMonth(state, monthIndex, totalShares) {
  const monthNumber = monthIndex + 1;
  const weights = customVestingWeights(state);
  const events = customVestingEvents(state);
  const vestingYears =
    state.vestingCadence === "custom" && state.customVestingMode === "weights"
      ? weights.length
      : state.vestingYears;
  const totalMonths = Math.max(1, vestingYears * 12);
  const interval = vestingInterval(state);

  if (state.vestingCadence === "custom" && state.customVestingMode === "events") {
    const event = events.find((item) => item.month === monthNumber);
    return event ? event.shares : 0;
  }

  if (monthNumber <= state.cliffMonths) return 0;
  if (monthNumber > totalMonths) return 0;
  if (monthNumber % interval !== 0) return 0;

  if (state.vestingCadence === "custom") {
    const yearIndex = Math.floor(monthIndex / 12);
    const monthInYear = monthIndex % 12;
    if ((monthInYear + 1) % interval !== 0) return 0;
    const weightTotal = Math.max(1, weights.reduce((sum, weight) => sum + weight, 0));
    const yearlyShares = totalShares * ((weights[yearIndex] || 0) / weightTotal);
    const eventsInYear = Math.max(1, 12 / interval);
    return yearlyShares / eventsInYear;
  }

  return totalShares / Math.max(1, totalMonths / interval);
}

function projectionFor(state, defaults, customGrowth = state.annualEquityGrowth) {
  const months = Math.max(1, Math.round(state.years * 12));
  const eventShares = customVestingEvents(state).reduce((sum, event) => sum + event.shares, 0);
  const totalShares =
    state.vestingCadence === "custom" && state.customVestingMode === "events"
      ? eventShares
      : state.rsuGrantValue / Math.max(1, state.startingSharePrice);
  const monthlyEquityGrowth = (1 + customGrowth / 100) ** (1 / 12) - 1;
  let cumulativeEquityValue = 0;
  const hasImmediateVesting = customVestingEvents(state).some((event) => event.month === 0);
  const rowIndexes = [
    ...(hasImmediateVesting ? [-1] : []),
    ...Array.from({ length: months }, (_, index) => index),
  ];

  const rows = rowIndexes.map((index) => {
    const vestingMonthNumber = index + 1;
    const compYearIndex = Math.max(0, Math.ceil(vestingMonthNumber / 12) - 1);
    const yearIndex = Math.floor(Math.max(0, index) / 12);
    const cashflowDate = monthDate(state, defaults, index);
    const calendarMonth = cashflowDate.getMonth() + 1;
    const annualSalary = annualSalaryForYear(state, yearIndex);
    const salary = index >= 0 ? annualSalary / 12 : 0;
    const bonus = index >= 0 && calendarMonth === state.bonusMonth ? annualSalary * (state.bonusPercent / 100) : 0;
    const signOn = index >= 0 ? signOnForMonth(state, index) : 0;
    const projectedSharePrice = state.startingSharePrice * (1 + monthlyEquityGrowth) ** vestingMonthNumber;
    const sharesVested = vestingSharesForMonth(state, index, totalShares);
    const equityValueNative = sharesVested * projectedSharePrice;
    const salaryReported = convertCurrency(state, salary, state.cashCurrency);
    const bonusReported = convertCurrency(state, bonus, state.cashCurrency);
    const signOnReported = convertCurrency(state, signOn, state.cashCurrency);
    const equityValue = convertCurrency(state, equityValueNative, state.equityCurrency);
    cumulativeEquityValue += equityValue;

    return {
      index,
      vestingMonthNumber,
      compYearIndex,
      month: monthLabel(state, defaults, index, "long"),
      vestingDate: vestingDateLabel(state, defaults, index),
      salary: salaryReported,
      bonus: bonusReported,
      signOn: signOnReported,
      cashTotal: salaryReported + bonusReported + signOnReported,
      projectedSharePrice,
      sharesVested,
      equityValue,
      cumulativeEquityValue,
      total: salaryReported + bonusReported + signOnReported + equityValue,
    };
  });

  const totals = rows.reduce(
    (acc, row) => {
      acc.salary += row.salary;
      acc.bonus += row.bonus;
      acc.signOn += row.signOn;
      acc.equity += row.equityValue;
      acc.total += row.total;
      acc.cash += row.cashTotal;
      return acc;
    },
    { salary: 0, bonus: 0, signOn: 0, equity: 0, total: 0, cash: 0 },
  );

  return {
    rows,
    totals,
    totalShares,
    peakMonth: rows.reduce((best, row) => (row.total > best.total ? row : best), rows[0]),
  };
}

function annualCashflowRows(rows) {
  const yearCount = Math.max(1, Math.max(...rows.map((row) => row.compYearIndex ?? Math.floor(row.index / 12))) + 1);
  return Array.from({ length: yearCount }, (_, yearIndex) => {
    const yearRows = rows.filter((row) => (row.compYearIndex ?? Math.floor(row.index / 12)) === yearIndex);
    const first = yearRows[0];
    const last = yearRows.at(-1);
    const totals = yearRows.reduce(
      (acc, row) => {
        acc.salary += row.salary;
        acc.bonus += row.bonus;
        acc.signOn += row.signOn;
        acc.equityValue += row.equityValue;
        acc.cashTotal += row.cashTotal;
        acc.total += row.total;
        return acc;
      },
      { salary: 0, bonus: 0, signOn: 0, equityValue: 0, cashTotal: 0, total: 0 },
    );

    return {
      ...totals,
      index: yearIndex,
      month: `Year ${yearIndex + 1}`,
      chartLabel: `Y${yearIndex + 1}`,
      detailLabel: `Year ${yearIndex + 1} (${first.month} - ${last.month})`,
    };
  });
}

function cashflowDisplayRows(state, defaults, model, view) {
  if (view === "annual") return annualCashflowRows(model.rows);
  return model.rows.map((row) => ({
    ...row,
    chartLabel: `${row.month.split(" ")[0]} '${monthLabel(state, defaults, row.index).split(" ")[1]?.slice(2) || ""}`,
    detailLabel: row.month,
  }));
}

function cumulativeCashflowRows(rows) {
  const running = { salary: 0, bonus: 0, signOn: 0, equityValue: 0, cashTotal: 0, total: 0 };
  return rows.map((row) => {
    running.salary += row.salary;
    running.bonus += row.bonus;
    running.signOn += row.signOn;
    running.equityValue += row.equityValue;
    running.cashTotal += row.cashTotal;
    running.total += row.total;
    return {
      ...row,
      salary: running.salary,
      bonus: running.bonus,
      signOn: running.signOn,
      equityValue: running.equityValue,
      cashTotal: running.cashTotal,
      total: running.total,
    };
  });
}

function visibleCashflowComponents(state) {
  return cashflowComponentMeta.filter((component) => state.cashflowComponents?.[component.key] !== false);
}

function normalizedCashflowWindow(state, totalRows) {
  const total = Math.max(1, totalRows);
  let start = Math.round(asNumber(state.cashflowWindowStart, 0));
  let end = Math.round(asNumber(state.cashflowWindowEnd, total));
  if (!state.cashflowWindowEnd || end <= 0) end = total;
  start = Math.min(total - 1, Math.max(0, start));
  end = Math.min(total, Math.max(start + 1, end));
  const visibleCount = Math.max(1, end - start);
  state.cashflowWindowStart = start;
  state.cashflowWindowEnd = end;
  state.cashflowZoom = total / visibleCount;
  return { start, end, total, visibleCount };
}

function cashflowWindowSelection(state, rows) {
  const window = normalizedCashflowWindow(state, rows.length);
  return { rows: rows.slice(window.start, window.end), window };
}

function resizeCashflowWindow(state, direction, totalRows, anchorRatio = 0.5) {
  const window = normalizedCashflowWindow(state, totalRows);
  const ratio = Math.min(1, Math.max(0, anchorRatio));
  const nextSize =
    direction === "in"
      ? Math.max(1, Math.floor(window.visibleCount * 0.72))
      : Math.min(window.total, Math.ceil(window.visibleCount / 0.72));
  const anchor = window.start + window.visibleCount * ratio;
  const start = Math.min(window.total - nextSize, Math.max(0, Math.round(anchor - nextSize * ratio)));
  state.cashflowWindowStart = start;
  state.cashflowWindowEnd = start + nextSize;
  state.cashflowZoom = window.total / nextSize;
}

function resetCashflowWindow(state, totalRows) {
  state.cashflowWindowStart = 0;
  state.cashflowWindowEnd = Math.max(1, totalRows);
  state.cashflowZoom = 1;
}

function selectCashflowWindowByRatios(state, totalRows, startRatio, endRatio) {
  const window = normalizedCashflowWindow(state, totalRows);
  const low = Math.min(startRatio, endRatio);
  const high = Math.max(startRatio, endRatio);
  const start = window.start + Math.floor(window.visibleCount * low);
  const end = window.start + Math.ceil(window.visibleCount * high);
  state.cashflowWindowStart = Math.min(window.total - 1, Math.max(0, start));
  state.cashflowWindowEnd = Math.min(window.total, Math.max(state.cashflowWindowStart + 1, end));
}

function cashflowZoomLabel(window) {
  const zoom = window.total / Math.max(1, window.visibleCount);
  return `Zoom ${Number.isInteger(zoom) ? zoom : zoom.toFixed(1)}x`;
}

function normalizedEquityWindow(state, totalRows) {
  const total = Math.max(1, totalRows);
  let start = Math.round(asNumber(state.equityWindowStart, 0));
  let end = Math.round(asNumber(state.equityWindowEnd, total));
  if (!state.equityWindowEnd || end <= 0) end = total;
  start = Math.min(total - 1, Math.max(0, start));
  end = Math.min(total, Math.max(start + 1, end));
  state.equityWindowStart = start;
  state.equityWindowEnd = end;
  return { start, end, total, visibleCount: Math.max(1, end - start) };
}

function equityWindowSelection(state, rows) {
  const window = normalizedEquityWindow(state, rows.length);
  return { rows: rows.slice(window.start, window.end), window };
}

function resizeEquityWindow(state, direction, totalRows, anchorRatio = 0.5) {
  const window = normalizedEquityWindow(state, totalRows);
  const ratio = Math.min(1, Math.max(0, anchorRatio));
  const nextSize =
    direction === "in"
      ? Math.max(1, Math.floor(window.visibleCount * 0.72))
      : Math.min(window.total, Math.ceil(window.visibleCount / 0.72));
  const anchor = window.start + window.visibleCount * ratio;
  const start = Math.min(window.total - nextSize, Math.max(0, Math.round(anchor - nextSize * ratio)));
  state.equityWindowStart = start;
  state.equityWindowEnd = start + nextSize;
}

function resetEquityWindow(state, totalRows) {
  state.equityWindowStart = 0;
  state.equityWindowEnd = Math.max(1, totalRows);
}

function selectEquityWindowByRatios(state, totalRows, startRatio, endRatio) {
  const window = normalizedEquityWindow(state, totalRows);
  const low = Math.min(startRatio, endRatio);
  const high = Math.max(startRatio, endRatio);
  const start = window.start + Math.floor(window.visibleCount * low);
  const end = window.start + Math.ceil(window.visibleCount * high);
  state.equityWindowStart = Math.min(window.total - 1, Math.max(0, start));
  state.equityWindowEnd = Math.min(window.total, Math.max(state.equityWindowStart + 1, end));
}

function equityZoomLabel(window) {
  const zoom = window.total / Math.max(1, window.visibleCount);
  return `Zoom ${Number.isInteger(zoom) ? zoom : zoom.toFixed(1)}x`;
}

function totalsForRows(rows) {
  return rows.reduce(
    (acc, row) => {
      acc.salary += row.salary;
      acc.bonus += row.bonus;
      acc.signOn += row.signOn;
      acc.equity += row.equityValue;
      acc.total += row.total;
      return acc;
    },
    { salary: 0, bonus: 0, signOn: 0, equity: 0, total: 0 },
  );
}

function mixRows(state, model) {
  if (state.mixPeriod === "all") return model.rows;
  const yearIndex = asNumber(state.mixPeriod.replace("year-", ""), 1) - 1;
  return model.rows.filter((row) => (row.compYearIndex ?? Math.floor(row.index / 12)) === yearIndex);
}

function mixPeriodOptions(state) {
  const yearCount = Math.max(1, Math.round(state.years));
  return [
    ["all", "All years"],
    ...Array.from({ length: yearCount }, (_, index) => [`year-${index + 1}`, `Year ${index + 1}`]),
  ];
}

function polarPoint(cx, cy, radius, angle) {
  const radians = ((angle - 90) * Math.PI) / 180;
  return {
    x: cx + radius * Math.cos(radians),
    y: cy + radius * Math.sin(radians),
  };
}

function donutSegmentPath(startPercent, endPercent) {
  const cx = 100;
  const cy = 100;
  const outerRadius = 88;
  const innerRadius = 52;
  const startAngle = startPercent * 3.6;
  const rawEndAngle = endPercent * 3.6;
  const endAngle = rawEndAngle - startAngle >= 360 ? rawEndAngle - 0.01 : rawEndAngle;
  const largeArc = endAngle - startAngle > 180 ? 1 : 0;
  const outerStart = polarPoint(cx, cy, outerRadius, startAngle);
  const outerEnd = polarPoint(cx, cy, outerRadius, endAngle);
  const innerStart = polarPoint(cx, cy, innerRadius, startAngle);
  const innerEnd = polarPoint(cx, cy, innerRadius, endAngle);

  return [
    `M ${outerStart.x.toFixed(3)} ${outerStart.y.toFixed(3)}`,
    `A ${outerRadius} ${outerRadius} 0 ${largeArc} 1 ${outerEnd.x.toFixed(3)} ${outerEnd.y.toFixed(3)}`,
    `L ${innerEnd.x.toFixed(3)} ${innerEnd.y.toFixed(3)}`,
    `A ${innerRadius} ${innerRadius} 0 ${largeArc} 0 ${innerStart.x.toFixed(3)} ${innerStart.y.toFixed(3)}`,
    "Z",
  ].join(" ");
}

function scenarioVariants(state, defaults) {
  const baseTotal = projectionFor(state, defaults, 0).totals.total;
  return scenarioGrowthRates.map((growth) => {
    const model = projectionFor(state, defaults, growth);
    const delta = model.totals.total - baseTotal;
    return { growth, total: model.totals.total, delta, annualRows: annualCashflowRows(model.rows) };
  });
}

function projectionPeriodLabel(state, defaults) {
  return `${parseStartDate(state, defaults).toISOString()} ${addMonths(parseStartDate(state, defaults), state.years * 12).toISOString()}`;
}


// dom.js
function byId(id) {
  const element = document.getElementById(id);
  if (!element) throw new Error(`Missing element #${id}`);
  return element;
}

function setHtml(id, html) {
  byId(id).innerHTML = html;
}

function setText(id, value) {
  byId(id).textContent = value;
}

function setActiveBySelector(selector, predicate) {
  document.querySelectorAll(selector).forEach((element) => {
    element.classList.toggle("is-active", predicate(element));
  });
}


// components/controls.js
function renderControlPanel({ state, saveState, render, renderControls }) {
  const container = document.getElementById("assumptionControls");
  container.innerHTML = "";

  const groups = [
    {
      title: "Projection",
      fields: [
        field({ state, saveState, render }, "Years", "years", "number", { min: 1, max: 10, step: 1 }),
        field({ state, saveState, render }, "Start Date", "startDate", "date"),
      ],
    },
    {
      title: "Currency & FX",
      fields: [
        selectField({ state, saveState, render, renderControls }, "Cash Currency", "cashCurrency", [
          ["SGD", "SGD"],
          ["USD", "USD"],
        ]),
        selectField({ state, saveState, render, renderControls }, "Equity Currency", "equityCurrency", [
          ["USD", "USD"],
          ["SGD", "SGD"],
        ]),
        selectField({ state, saveState, render, renderControls }, "Report Currency", "reportCurrency", [
          ["SGD", "SGD"],
          ["USD", "USD"],
        ]),
        field({ state, saveState, render }, "USD to SGD", "usdToSgd", "number", { min: 0.0001, step: "any" }),
      ],
    },
    {
      title: "Cash Compensation",
      fields: [
        field({ state, saveState, render }, "Base Salary", "baseSalary", "number", { min: 0, step: 1000 }),
        selectField({ state, saveState, render, renderControls }, "Salary Basis", "salaryBasis", [
          ["annual", "Annual"],
          ["monthly", "Monthly"],
        ]),
        field({ state, saveState, render }, "Salary Growth %", "salaryGrowth", "number", { step: 0.5 }),
        field({ state, saveState, render }, "Bonus %", "bonusPercent", "number", { min: 0, step: 1 }),
        selectField({ state, saveState, render, renderControls }, "Bonus Month", "bonusMonth", monthOptions()),
      ],
    },
    {
      title: "Sign-on Bonuses",
      fields: [
        field({ state, saveState, render }, "Year 1 Amount", "signOnYear1", "number", { min: 0, step: 1000 }),
        segmentedField({ state, saveState, render, renderControls }, "signOnYear1Mode", ["lump", "monthly"]),
        field({ state, saveState, render }, "Year 2 Amount", "signOnYear2", "number", { min: 0, step: 1000 }),
        segmentedField({ state, saveState, render, renderControls }, "signOnYear2Mode", ["lump", "monthly"]),
      ],
    },
    {
      title: "Equity",
      fields: [
        field({ state, saveState, render }, "RSU Grant Value", "rsuGrantValue", "number", { min: 0, step: 1000 }),
        field({ state, saveState, render }, "Starting Price", "startingSharePrice", "number", { min: 1, step: 1 }),
        field({ state, saveState, render }, "Equity Growth %", "annualEquityGrowth", "number", { step: 1 }),
        ...(state.vestingCadence === "custom"
          ? []
          : [field({ state, saveState, render }, "Vesting Years", "vestingYears", "number", { min: 1, max: 8, step: 1 })]),
        selectField({ state, saveState, render, renderControls }, "Vesting Cadence", "vestingCadence", [
          ["custom", "Custom"],
          ["monthly", "Monthly"],
          ["quarterly", "Quarterly"],
          ["annual", "Annual"],
        ]),
        ...(state.vestingCadence === "custom"
          ? [
              selectField({ state, saveState, render, renderControls }, "Custom Type", "customVestingMode", [
                ["weights", "Year weights"],
                ["events", "Vesting events"],
              ]),
              field({ state, saveState, render }, "Custom Schedule", "customVestingPattern", "text", {
                placeholder:
                  state.customVestingMode === "events"
                    ? "30:98,36:97,42:76,48:75"
                    : "5:15:45:35",
                help:
                  state.customVestingMode === "events"
                    ? "Use comma-separated month:units pairs, e.g. 30:98,36:97,42:76,48:75."
                    : "",
                full: true,
              }),
              ...(state.customVestingMode === "events"
                ? []
                : [
                    selectField({ state, saveState, render, renderControls }, "Spread", "customVestingSpread", [
                      ["monthly", "Monthly"],
                      ["quarterly", "Quarterly"],
                      ["annual", "Annual"],
                    ]),
                  ]),
            ]
          : []),
        selectField({ state, saveState, render, renderControls }, "Cliff", "cliffMonths", [
          [0, "No cliff"],
          [12, "12 months"],
        ]),
      ],
    },
  ];

  groups.forEach((group) => {
    const wrapper = document.createElement("section");
    wrapper.className = "control-group";
    wrapper.innerHTML = `<h3 class="group-title">${group.title}</h3><div class="field-grid"></div>`;
    const grid = wrapper.querySelector(".field-grid");
    group.fields.forEach((node) => grid.appendChild(node));
    container.appendChild(wrapper);
  });
}

function field(context, labelText, key, type, options = {}) {
  const { state, saveState, render } = context;
  const wrapper = document.createElement("label");
  wrapper.className = "field";
  if (options.full) wrapper.classList.add("full");
  const input = document.createElement("input");
  input.type = type;
  input.value = state[key];
  Object.entries(options)
    .filter(([name]) => !["full", "help"].includes(name))
    .forEach(([name, value]) => input.setAttribute(name, value));
  input.addEventListener("input", () => {
    state[key] = type === "number" ? asNumber(input.value) : input.value;
    saveState();
    render();
  });
  const labelRow = document.createElement("span");
  labelRow.className = "field-label-row";
  labelRow.append(labelText);
  if (options.help) {
    const help = document.createElement("span");
    help.className = "field-help";
    help.textContent = options.help;
    labelRow.appendChild(help);
  }
  wrapper.append(labelRow, input);
  return wrapper;
}

function selectField(context, labelText, key, options) {
  const { state, saveState, render, renderControls } = context;
  const wrapper = document.createElement("label");
  wrapper.className = "field";
  const select = document.createElement("select");
  options.forEach(([value, label]) => {
    const option = document.createElement("option");
    option.value = value;
    option.textContent = label;
    option.selected = String(state[key]) === String(value);
    select.appendChild(option);
  });
  select.addEventListener("change", () => {
    state[key] = Number.isNaN(Number(select.value)) ? select.value : Number(select.value);
    saveState();
    if (["vestingCadence", "customVestingMode"].includes(key)) renderControls();
    render();
  });
  wrapper.append(labelText, select);
  return wrapper;
}

function segmentedField(context, key, values) {
  const { state, saveState, render, renderControls } = context;
  const wrapper = document.createElement("div");
  wrapper.className = "field";
  const label = document.createElement("label");
  label.textContent = key.includes("Year1") ? "Year 1 Payout" : "Year 2 Payout";
  const segmented = document.createElement("div");
  segmented.className = "segmented";
  values.forEach((value) => {
    const button = document.createElement("button");
    button.type = "button";
    button.textContent = value === "lump" ? "Lump" : "Monthly";
    button.classList.toggle("is-active", state[key] === value);
    button.addEventListener("click", () => {
      state[key] = value;
      saveState();
      renderControls();
      render();
    });
    segmented.appendChild(button);
  });
  wrapper.append(label, segmented);
  return wrapper;
}


// components/charts.js
function renderCashflowChart(state, defaults, model) {
  const baseRows = cashflowDisplayRows(state, defaults, model, state.overviewCashflowView);
  const allRows = state.overviewCashflowCumulative ? cumulativeCashflowRows(baseRows) : baseRows;
  const { rows, window } = cashflowWindowSelection(state, allRows);
  const visibleComponents = visibleCashflowComponents(state);
  const visibleTotal = (row) => visibleComponents.reduce((sum, component) => sum + row[component.key], 0);
  const peak = rows.reduce((best, row) => (visibleTotal(row) > visibleTotal(best) ? row : best), rows[0]);
  const isFitWidth = window.visibleCount === window.total;
  const width = isFitWidth ? 980 : Math.max(980, rows.length * 32 + 82);
  const minWidth = isFitWidth ? "100%" : `${width}px`;
  const height = 300;
  const pad = { top: 18, right: 12, bottom: 34, left: 58 };
  const plotWidth = width - pad.left - pad.right;
  const plotHeight = height - pad.top - pad.bottom;
  const max = Math.max(...rows.map(visibleTotal), 1);
  const barGap = 2;
  const barWidth = Math.max(4, plotWidth / rows.length - barGap);
  const y = (value) => pad.top + plotHeight - (value / max) * plotHeight;
  const barSegments = rows
    .map((row, index) => {
      const x = pad.left + index * (plotWidth / rows.length);
      let stackY = pad.top + plotHeight;
      return visibleComponents
        .map((component) => {
          const value = row[component.key];
          const h = (value / max) * plotHeight;
          stackY -= h;
          const label = `${row.detailLabel}: ${component.label} ${money(state, value)}`;
          return `<rect class="bar ${component.className}" x="${x.toFixed(2)}" y="${stackY.toFixed(2)}" width="${barWidth.toFixed(2)}" height="${Math.max(0, h).toFixed(2)}"><title>${escapeHtml(label)}</title></rect>`;
        })
        .join("");
    })
    .join("");
  const grid = [0.25, 0.5, 0.75, 1]
    .map((ratio) => {
      const value = max * ratio;
      const yy = y(value);
      return `<line class="grid-line" x1="${pad.left}" x2="${width - pad.right}" y1="${yy}" y2="${yy}"></line><text class="axis-label y-axis-label" x="8" y="${yy + 4}">${compactMoney(state, value)}</text>`;
    })
    .join("");
  const labels = rows
    .filter((_, index) => index % Math.max(1, Math.ceil(rows.length / 8)) === 0)
    .map((row, index) => {
      const actualIndex = rows.indexOf(row);
      const x = pad.left + actualIndex * (plotWidth / rows.length) + barWidth / 2;
      return `<text class="axis-label x-axis-label" x="${x}" y="${height - 8}" text-anchor="middle">${row.chartLabel}</text>`;
    })
    .join("");

  document.getElementById("cashflowChart").innerHTML = `
    <svg viewBox="0 0 ${width} ${height}" style="min-width:${minWidth}" role="img" aria-label="Compensation cashflow chart">
      ${grid}
      ${barSegments}
      ${labels}
    </svg>
  `;
  document.getElementById("peakBadge").textContent = `Peak: ${peak.month}`;
  renderCashflowWindowPane(state, allRows, window, visibleComponents);
}

function renderCashflowWindowPane(state, rows, window, visibleComponents) {
  const visibleTotal = (row) => visibleComponents.reduce((sum, component) => sum + row[component.key], 0);
  const max = Math.max(...rows.map(visibleTotal), 1);
  const overview = document.getElementById("cashflowWindowOverview");

  overview.innerHTML = rows
    .map((row, index) => {
      const height = Math.max(3, (visibleTotal(row) / max) * 38);
      const selected = index >= window.start && index < window.end;
      return `<span class="cashflow-window-bar ${selected ? "is-selected" : ""}" style="height:${height.toFixed(1)}px" title="${row.month}: ${money(state, visibleTotal(row))}"></span>`;
    })
    .join("");

  const startInput = document.getElementById("cashflowWindowStart");
  const endInput = document.getElementById("cashflowWindowEnd");
  startInput.max = Math.max(0, rows.length - 1);
  endInput.max = rows.length;
  startInput.value = window.start;
  endInput.value = window.end;
  const periodName = state.overviewCashflowView === "annual" ? "years" : "months";
  const first = rows[window.start];
  const last = rows[window.end - 1] || first;
  document.getElementById("cashflowWindowLabel").textContent =
    window.visibleCount === window.total
      ? `Selected: All ${periodName}`
      : `Selected: ${first.month} - ${last.month} (${window.visibleCount}/${window.total} ${periodName})`;
  document.getElementById("cashflowZoomLabel").textContent = cashflowZoomLabel(window);
  document.querySelector("[data-cashflow-zoom='out']").disabled = window.visibleCount >= window.total;
  document.querySelector("[data-cashflow-zoom='in']").disabled = window.visibleCount <= 1;
}

function renderEquityChart(state, model) {
  const allRows = model.rows;
  const { rows, window } = equityWindowSelection(state, allRows);
  const vestRows = rows.filter((row) => row.sharesVested > 0);
  const points = rows.map((row) => row.cumulativeEquityValue);
  const isFitWidth = window.visibleCount === window.total;
  const width = isFitWidth ? 980 : Math.max(980, rows.length * 34 + 96);
  const minWidth = isFitWidth ? "100%" : `${width}px`;
  const height = 300;
  const pad = { top: 18, right: 16, bottom: 34, left: 62 };
  const plotWidth = width - pad.left - pad.right;
  const plotHeight = height - pad.top - pad.bottom;
  const max = Math.max(...points, 1);
  const x = (index) => pad.left + (index / Math.max(1, points.length - 1)) * plotWidth;
  const y = (value) => pad.top + plotHeight - (value / max) * plotHeight;
  const path = points.map((point, index) => `${index === 0 ? "M" : "L"} ${x(index).toFixed(2)} ${y(point).toFixed(2)}`).join(" ");
  const dots = vestRows
    .map((row) => {
      const pointIndex = rows.indexOf(row);
      const label = `${row.month} Vesting: ${numberFormatter.format(row.sharesVested)} shares, vested ${money(state, row.equityValue)}, cumulative ${money(state, row.cumulativeEquityValue)}`;
      return `
        <circle class="equity-point" cx="${x(pointIndex)}" cy="${y(row.cumulativeEquityValue)}" r="4"></circle>
        <circle class="equity-point-hit" cx="${x(pointIndex)}" cy="${y(row.cumulativeEquityValue)}" r="13" data-equity-index="${row.index}" aria-hidden="true"><title>${escapeHtml(label)}</title></circle>
      `;
    })
    .join("");
  const grid = [0.25, 0.5, 0.75, 1]
    .map((ratio) => {
      const value = max * ratio;
      const yy = y(value);
      return `<line class="grid-line" x1="${pad.left}" x2="${width - pad.right}" y1="${yy}" y2="${yy}"></line><text class="axis-label y-axis-label" x="8" y="${yy + 4}">${compactMoney(state, value)}</text>`;
    })
    .join("");
  const labels = rows
    .filter((_, index) => index % Math.max(1, Math.ceil(rows.length / 8)) === 0)
    .map((row) => `<text class="axis-label x-axis-label" x="${x(rows.indexOf(row))}" y="${height - 8}" text-anchor="middle">${row.month.split(" ")[0]}</text>`)
    .join("");

  document.getElementById("equityChart").innerHTML = `
    <svg viewBox="0 0 ${width} ${height}" style="min-width:${minWidth}" role="img" aria-label="Equity valuation growth chart">
      ${grid}
      <path class="equity-line" d="${path}"></path>
      ${dots}
      ${labels}
    </svg>
  `;
  document.getElementById("equityZoomLabel").textContent = equityZoomLabel(window);
  renderEquityWindowPane(state, allRows, window);
  renderEquityPointDetail(state, model);
}

function renderEquityWindowPane(state, rows, window) {
  const max = Math.max(...rows.map((row) => row.cumulativeEquityValue), 1);
  const overview = document.getElementById("equityWindowOverview");

  overview.innerHTML = rows
    .map((row, index) => {
      const height = Math.max(3, (row.cumulativeEquityValue / max) * 38);
      const selected = index >= window.start && index < window.end;
      return `<span class="cashflow-window-bar ${selected ? "is-selected" : ""}" style="height:${height.toFixed(1)}px" title="${row.month}: ${money(state, row.cumulativeEquityValue)}"></span>`;
    })
    .join("");

  const startInput = document.getElementById("equityWindowStart");
  const endInput = document.getElementById("equityWindowEnd");
  startInput.max = Math.max(0, rows.length - 1);
  endInput.max = rows.length;
  startInput.value = window.start;
  endInput.value = window.end;
  const first = rows[window.start];
  const last = rows[window.end - 1] || first;
  document.getElementById("equityWindowLabel").textContent =
    window.visibleCount === window.total
      ? "Selected: All months"
      : `Selected: ${first.month} - ${last.month} (${window.visibleCount}/${window.total} months)`;
}

function renderEquityPointDetail(state, model, rowIndex = state.selectedEquityPoint) {
  const detail = document.getElementById("equityPointDetail");
  const row = model.rows.find((item) => item.index === Number(rowIndex));
  if (!row || row.sharesVested <= 0) {
    detail.textContent = "Select a point to inspect vested value and cumulative equity.";
    return;
  }
  detail.textContent = `${row.month}: Vested ${numberFormatter.format(row.sharesVested)} shares worth ${money(state, row.equityValue)}. Cumulative equity: ${money(state, row.cumulativeEquityValue)}. Share price: ${money(state, row.projectedSharePrice, state.equityCurrency)}.`;
}

function renderMix(state, model) {
  const selectedRows = mixRows(state, model);
  const totals = totalsForRows(selectedRows);
  const total = Math.max(1, totals.total);
  const parts = [
    ["Salary", totals.salary, "salary"],
    ["Bonus", totals.bonus, "bonus"],
    ["Sign-on", totals.signOn, "signon"],
    ["Equity", totals.equity, "equity"],
  ];
  const percentLabel = (value) => `${((value / total) * 100).toFixed(1)}%`;
  let mixCursor = 0;
  const mixParts = parts.map(([label, value, className]) => {
    const percent = (value / total) * 100;
    const part = {
      label,
      value,
      className,
      percent,
      start: mixCursor,
      end: mixCursor + percent,
      detail: `${label}: ${money(state, value)} (${percentLabel(value)})`,
    };
    mixCursor += percent;
    return part;
  });
  const optionMarkup = mixPeriodOptions(state)
    .map(([value, label]) => `<option value="${value}" ${state.mixPeriod === value ? "selected" : ""}>${label}</option>`)
    .join("");
  const periodLabel =
    state.mixPeriod === "all"
      ? "Projected total over the horizon."
      : `${mixPeriodOptions(state).find(([value]) => value === state.mixPeriod)?.[1] || "Selected year"} compensation mix.`;

  document.getElementById("mixPeriodLabel").textContent = periodLabel;

  document.getElementById("mixChart").innerHTML = `
    <div class="mix-controls">
      <label class="field inline-select">Mix Period
        <select id="mixPeriodSelect">${optionMarkup}</select>
      </label>
    </div>
    <svg class="mix-donut" viewBox="0 0 200 200" role="img" aria-label="Compensation mix by component">
      ${mixParts
        .map(
          (part) => `
          <path
            class="mix-segment ${part.className}"
            d="${donutSegmentPath(part.start, part.end)}"
            tabindex="0"
            data-mix-detail="${escapeHtml(part.detail)}"
            aria-label="${escapeHtml(part.detail)}"
          >
            <title>${escapeHtml(part.detail)}</title>
          </path>
        `,
        )
        .join("")}
      <circle class="mix-donut-hole" cx="100" cy="100" r="50"></circle>
    </svg>
    <div id="mixHoverDetail" class="mix-detail-label">Total mix: ${money(state, totals.total)}</div>
    <div class="legend">
      ${parts
        .map(
          ([label, value, className]) => `
          <div class="legend-row">
            <span><i class="dot ${className}"></i>${label}</span>
            <strong><span>${money(state, value)}</span><span class="mix-percent">${percentLabel(value)}</span></strong>
          </div>
        `,
        )
        .join("")}
    </div>
  `;
  const mixDetail = document.getElementById("mixHoverDetail");
  const defaultMixDetail = `Total mix: ${money(state, totals.total)}`;
  document.querySelectorAll(".mix-segment").forEach((segment) => {
    const showDetail = () => {
      mixDetail.textContent = segment.dataset.mixDetail;
    };
    segment.addEventListener("mouseenter", showDetail);
    segment.addEventListener("focus", showDetail);
    segment.addEventListener("click", showDetail);
  });
  document.querySelector(".mix-donut").addEventListener("mouseleave", () => {
    mixDetail.textContent = defaultMixDetail;
  });
}


// components/tables.js
function renderSummary(state, model) {
  const cards = [
    ["Total Projected Comp", model.totals.total, `${state.years} year horizon`],
    ["Cash Compensation", model.totals.cash, `Salary, bonus, and sign-on in ${state.reportCurrency}`],
    ["Equity Value", model.totals.equity, `${numberFormatter.format(model.totalShares)} granted shares`],
    ["Peak Month", model.peakMonth.total, model.peakMonth.month],
  ];

  document.getElementById("summaryCards").innerHTML = cards
    .map(
      ([label, value, note]) => `
        <article class="summary-card">
          <p>${label}</p>
          <strong>${money(state, value)}</strong>
          <span>${note}</span>
        </article>
      `,
    )
    .join("");

  document.getElementById("peakBadge").textContent = `Peak: ${model.peakMonth.month}`;
  document.getElementById("cashflowTotal").textContent = `Total: ${money(state, model.totals.total)}`;
}

function renderTables(state, defaults, model) {
  const vestRows = model.rows.filter((row) => row.sharesVested > 0);
  const baseCashRows = cashflowDisplayRows(state, defaults, model, state.detailCashflowView);
  const cashRows = state.detailCashflowCumulative ? cumulativeCashflowRows(baseCashRows) : baseCashRows;
  const cashSubtotals = totalsForRows(baseCashRows);
  const vestMarkup = (rows) =>
    rows
      .map(
        (row) => `
        <tr>
          <td>${row.vestingDate}</td>
          <td>${numberFormatter.format(row.sharesVested)}</td>
          <td>${money(state, row.projectedSharePrice, state.equityCurrency)}</td>
          <td>${money(state, row.equityValue)}</td>
          <td>${money(state, row.cumulativeEquityValue)}</td>
        </tr>
      `,
      )
      .join("");

  document.getElementById("vestingPreview").innerHTML = vestMarkup(vestRows.slice(0, 8));
  document.getElementById("vestingRows").innerHTML = vestMarkup(vestRows);
  document.getElementById("cashflowRows").innerHTML = cashRows
    .map(
      (row) => `
      <tr>
        <td>${row.detailLabel}</td>
        <td>${money(state, row.salary)}</td>
        <td>${money(state, row.bonus)}</td>
        <td>${money(state, row.signOn)}</td>
        <td>${money(state, row.equityValue)}</td>
        <td>${money(state, row.total)}</td>
      </tr>
    `,
    )
    .join("");
  document.getElementById("cashflowSubtotal").innerHTML = `
    <tr>
      <td>Subtotal</td>
      <td>${money(state, cashSubtotals.salary)}</td>
      <td>${money(state, cashSubtotals.bonus)}</td>
      <td>${money(state, cashSubtotals.signOn)}</td>
      <td>${money(state, cashSubtotals.equity)}</td>
      <td>${money(state, cashSubtotals.total)}</td>
    </tr>
  `;
}

function renderEquityStats(state, model) {
  const finalPrice = model.rows.at(-1)?.projectedSharePrice || state.startingSharePrice;
  const stats = [
    ["Implied shares", numberFormatter.format(model.totalShares)],
    ["Starting price", money(state, state.startingSharePrice, state.equityCurrency)],
    ["Final projected price", money(state, finalPrice, state.equityCurrency)],
    ["Cumulative vested value", money(state, model.totals.equity)],
    ["Average vesting event", money(state, model.totals.equity / Math.max(1, model.rows.filter((row) => row.sharesVested > 0).length))],
  ];

  document.getElementById("equityStats").innerHTML = stats
    .map(
      ([label, value]) => `
      <div class="stat-row">
        <span>${label}</span>
        <strong>${value}</strong>
      </div>
    `,
    )
    .join("");
}

function renderScenarios(state, defaults) {
  const variants = scenarioVariants(state, defaults);
  const yearCount = Math.max(1, Math.round(state.years));

  document.getElementById("scenarioGrid").innerHTML = variants
    .map(
      (item) => `
      <div class="scenario-row">
        <span>${item.growth}% annual equity growth</span>
        <strong>${money(state, item.total)} (${item.delta >= 0 ? "+" : ""}${compactMoney(state, item.delta)})</strong>
      </div>
    `,
    )
    .join("");

  document.getElementById("scenarioYearHead").innerHTML = `
    <tr>
      <th>Growth</th>
      ${Array.from({ length: yearCount }, (_, index) => `<th>Year ${index + 1}</th>`).join("")}
      <th>Total</th>
    </tr>
  `;
  document.getElementById("scenarioYearRows").innerHTML = variants
    .map(
      (item) => `
      <tr>
        <td>${item.growth}%</td>
        ${Array.from({ length: yearCount }, (_, index) => `<td>${money(state, item.annualRows[index]?.total || 0)}</td>`).join("")}
        <td>${money(state, item.total)}</td>
      </tr>
    `,
    )
    .join("");
}


// export.js
function exportFile(content, fileName, type) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function exportCsv(state, defaults) {
  const model = projectionFor(state, defaults);
  const header = [
    "Month",
    `Salary (${state.reportCurrency})`,
    `Bonus (${state.reportCurrency})`,
    `Sign-on (${state.reportCurrency})`,
    "Shares Vested",
    `Projected Share Price (${state.equityCurrency})`,
    `Equity Value (${state.reportCurrency})`,
    `Total (${state.reportCurrency})`,
  ];
  const rows = model.rows.map((row) => [
    row.month,
    row.salary.toFixed(2),
    row.bonus.toFixed(2),
    row.signOn.toFixed(2),
    row.sharesVested.toFixed(4),
    row.projectedSharePrice.toFixed(2),
    row.equityValue.toFixed(2),
    row.total.toFixed(2),
  ]);
  const csv = [header, ...rows].map((line) => line.join(",")).join("\n");
  exportFile(csv, safeFileName(state.scenarioName, ".csv"), "text/csv;charset=utf-8");
}

function tableRows(rows, cells) {
  return rows
    .map((row) => `<tr>${cells.map((cell) => `<td>${escapeHtml(cell(row))}</td>`).join("")}</tr>`)
    .join("");
}

function exportHtmlReport(state, defaults) {
  const model = projectionFor(state, defaults);
  const annualRows = annualCashflowRows(model.rows);
  const monthlyRows = cashflowDisplayRows(state, defaults, model, "monthly");
  const vestRows = model.rows.filter((row) => row.sharesVested > 0);
  const yearCount = Math.max(1, Math.round(state.years));
  const horizonLabel = `${yearCount} year horizon`;
  const includeScenarios = Number(state.rsuGrantValue || 0) > 0;
  const variants = scenarioVariants(state, defaults);
  const assumptions = [
    ["Projection period", `${exactDateLabel(parseStartDate(state, defaults))} to ${exactDateLabel(addMonths(parseStartDate(state, defaults), state.years * 12))}`],
    ["Base salary", `${money(state, state.baseSalary, state.cashCurrency)} ${state.salaryBasis}`],
    ["Bonus", `${numberFormatter.format(state.bonusPercent)}% paid in ${monthOptions().find(([month]) => month === state.bonusMonth)?.[1] || "selected month"}`],
    ["Sign-on bonus", `Year 1 ${money(state, state.signOnYear1, state.cashCurrency)} (${state.signOnYear1Mode}), Year 2 ${money(state, state.signOnYear2, state.cashCurrency)} (${state.signOnYear2Mode})`],
    ["RSU grant", `${money(state, state.rsuGrantValue, state.equityCurrency)} at ${money(state, state.startingSharePrice, state.equityCurrency)} starting price`],
    ["Equity growth", `${numberFormatter.format(state.annualEquityGrowth)}% annually`],
    ["Currencies", `Cash ${state.cashCurrency}, equity ${state.equityCurrency}, report ${state.reportCurrency}, USD/SGD ${currencyRateFormatter.format(state.usdToSgd)}`],
    ["Vesting", state.vestingCadence === "custom" ? `${state.customVestingMode}: ${state.customVestingPattern}` : `${state.vestingCadence}, ${state.vestingYears} years`],
  ];

  const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>${escapeHtml(state.scenarioName)} Report</title>
    <style>
      body { margin: 32px; color: #14211f; font-family: Inter, Arial, sans-serif; line-height: 1.45; }
      header { border-bottom: 2px solid #d9e6e1; margin-bottom: 24px; padding-bottom: 16px; }
      h1 { margin: 0 0 6px; font-size: 28px; }
      h2 { margin: 28px 0 10px; font-size: 18px; }
      p { margin: 0 0 10px; color: #60716d; }
      .summary { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; }
      .card { border: 1px solid #d9e6e1; border-radius: 8px; padding: 12px; }
      .card span { display: block; color: #60716d; font-size: 12px; font-weight: 700; text-transform: uppercase; }
      .card strong { display: block; margin-top: 4px; font-size: 18px; }
      table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 13px; }
      th, td { border-bottom: 1px solid #e6efec; padding: 8px; text-align: right; }
      th:first-child, td:first-child { text-align: left; }
      th { color: #60716d; font-size: 11px; text-transform: uppercase; }
      .assumptions td:nth-child(2) { text-align: left; }
      .note { margin-top: 24px; padding: 12px; border-radius: 8px; background: #eef7f4; color: #24534b; font-weight: 700; }
      @media print { body { margin: 18mm; } .summary { grid-template-columns: repeat(2, minmax(0, 1fr)); } }
    </style>
  </head>
  <body>
    <header>
      <h1>${escapeHtml(state.scenarioName)}</h1>
      <p>Compensation projection report generated from the dashboard. Print or save as PDF from your browser to share a fixed copy.</p>
    </header>
    <section>
      <h2>Projection Summary</h2>
      <div class="summary">
        <div class="card"><span>Total projected comp (${escapeHtml(horizonLabel)})</span><strong>${escapeHtml(money(state, model.totals.total))}</strong></div>
        <div class="card"><span>Cash compensation (${escapeHtml(horizonLabel)})</span><strong>${escapeHtml(money(state, model.totals.cash))}</strong></div>
        <div class="card"><span>Equity value</span><strong>${escapeHtml(money(state, model.totals.equity))}</strong></div>
        <div class="card"><span>Peak month</span><strong>${escapeHtml(model.peakMonth.month)}</strong></div>
      </div>
    </section>
    <section>
      <h2>Key Assumptions</h2>
      <table class="assumptions">
        <tbody>${assumptions.map(([label, value]) => `<tr><td>${escapeHtml(label)}</td><td>${escapeHtml(value)}</td></tr>`).join("")}</tbody>
      </table>
    </section>
    <section>
      <h2>Annual Cashflow</h2>
      <table>
        <thead><tr><th>Year</th><th>Salary</th><th>Bonus</th><th>Sign-on</th><th>Equity Value</th><th>Total</th></tr></thead>
        <tbody>${tableRows(annualRows, [
          (row) => row.month,
          (row) => money(state, row.salary),
          (row) => money(state, row.bonus),
          (row) => money(state, row.signOn),
          (row) => money(state, row.equityValue),
          (row) => money(state, row.total),
        ])}</tbody>
      </table>
    </section>
    <section>
      <h2>Monthly Cashflow</h2>
      <table>
        <thead><tr><th>Month</th><th>Salary</th><th>Bonus</th><th>Sign-on</th><th>Equity Value</th><th>Total</th></tr></thead>
        <tbody>${tableRows(monthlyRows, [
          (row) => row.detailLabel,
          (row) => money(state, row.salary),
          (row) => money(state, row.bonus),
          (row) => money(state, row.signOn),
          (row) => money(state, row.equityValue),
          (row) => money(state, row.total),
        ])}</tbody>
      </table>
    </section>
    ${
      includeScenarios
        ? `<section>
      <h2>Scenario Sensitivity</h2>
      <table>
        <thead>
          <tr>
            <th>Scenario</th>
            ${Array.from({ length: yearCount }, (_, index) => `<th>Year ${index + 1}</th>`).join("")}
            <th>Total</th>
            <th>Delta vs 0%</th>
          </tr>
        </thead>
        <tbody>${tableRows(variants, [
          (row) => `${row.growth}% annual equity growth`,
          ...Array.from({ length: yearCount }, (_, index) => (row) => money(state, row.annualRows[index]?.total || 0)),
          (row) => money(state, row.total),
          (row) => `${row.delta >= 0 ? "+" : ""}${money(state, row.delta)}`,
        ])}</tbody>
      </table>
    </section>`
        : ""
    }
    <section>
      <h2>Vesting Schedule</h2>
      <table>
        <thead><tr><th>Vesting Date</th><th>Shares Vesting</th><th>Projected Price</th><th>Vested Value</th><th>Cumulative Vested</th></tr></thead>
        <tbody>${tableRows(vestRows, [
          (row) => row.vestingDate,
          (row) => numberFormatter.format(row.sharesVested),
          (row) => money(state, row.projectedSharePrice, state.equityCurrency),
          (row) => money(state, row.equityValue),
          (row) => money(state, row.cumulativeEquityValue),
        ])}</tbody>
      </table>
    </section>
    <p class="note">Shareable options: send this HTML file directly, or open it and use Print or save as PDF.</p>
  </body>
</html>`;

  exportFile(html, safeFileName(state.scenarioName, "-report.html"), "text/html;charset=utf-8");
}


// main.js
const state = loadState();
let activeTab = "overview";

function saveState() {
  persistState(state);
}

function renderControls() {
  renderControlPanel({ state, saveState, render, renderControls });
}

function setActiveTab(tab) {
  activeTab = tab;
  document.querySelectorAll("[data-tab]").forEach((button) => {
    button.classList.toggle("is-active", button.dataset.tab === tab);
  });
  document.querySelectorAll(".tab-panel").forEach((panel) => {
    panel.classList.toggle("is-active", panel.id === tab);
  });
}

function normalizeState() {
  state.years = Math.min(10, Math.max(1, Math.round(asNumber(state.years, 4))));
  state.vestingYears = Math.min(8, Math.max(1, Math.round(asNumber(state.vestingYears, 4))));
  state.cashflowZoom = Math.max(1, Math.min(4, Math.round(asNumber(state.cashflowZoom, 1))));
  if (!state.cashflowComponents || typeof state.cashflowComponents !== "object") {
    state.cashflowComponents = { ...DEFAULTS.cashflowComponents };
  }
  cashflowComponentMeta.forEach((component) => {
    if (typeof state.cashflowComponents[component.key] !== "boolean") {
      state.cashflowComponents[component.key] = true;
    }
  });
  if (!cashflowComponentMeta.some((component) => state.cashflowComponents[component.key])) {
    state.cashflowComponents.salary = true;
  }
  if (!["annual", "monthly"].includes(state.salaryBasis)) {
    state.salaryBasis = "annual";
  }
  ["cashCurrency", "equityCurrency", "reportCurrency"].forEach((key) => {
    if (!["SGD", "USD"].includes(state[key])) state[key] = DEFAULTS[key];
  });
  if (state.cashflowView && !state.overviewCashflowView && !state.detailCashflowView) {
    state.overviewCashflowView = state.cashflowView;
    state.detailCashflowView = state.cashflowView;
  }
  if (!["monthly", "annual"].includes(state.overviewCashflowView)) {
    state.overviewCashflowView = "monthly";
  }
  if (!["monthly", "annual"].includes(state.detailCashflowView)) {
    state.detailCashflowView = "monthly";
  }
  state.overviewCashflowCumulative = Boolean(state.overviewCashflowCumulative);
  state.detailCashflowCumulative = Boolean(state.detailCashflowCumulative);
  const validMixPeriods = mixPeriodOptions(state).map(([value]) => value);
  if (!validMixPeriods.includes(state.mixPeriod)) {
    state.mixPeriod = "all";
  }
  state.usdToSgd = Math.max(0.0001, asNumber(state.usdToSgd, DEFAULTS.usdToSgd));
  if (!["weights", "events"].includes(state.customVestingMode)) {
    state.customVestingMode = "weights";
  }
  if (state.vestingCadence === "custom") {
    state.vestingYears =
      state.customVestingMode === "events"
        ? Math.ceil((customVestingEvents(state).at(-1)?.month || 12) / 12)
        : customVestingWeights(state).length;
  }
}

function render() {
  normalizeState();
  const model = projectionFor(state, DEFAULTS);
  document.getElementById("scenarioName").value = state.scenarioName;
  document.getElementById("periodLabel").textContent = `${exactDateLabel(parseStartDate(state, DEFAULTS))} - ${exactDateLabel(addMonths(parseStartDate(state, DEFAULTS), state.years * 12))}`;
  document.querySelectorAll("[data-overview-cashflow-view]").forEach((button) => {
    button.classList.toggle("is-active", button.dataset.overviewCashflowView === state.overviewCashflowView);
  });
  document.querySelectorAll("[data-detail-cashflow-view]").forEach((button) => {
    button.classList.toggle("is-active", button.dataset.detailCashflowView === state.detailCashflowView);
  });
  document.querySelector("[data-overview-cumulative]").classList.toggle("is-active", state.overviewCashflowCumulative);
  document.querySelector("[data-detail-cumulative]").classList.toggle("is-active", state.detailCashflowCumulative);
  document.querySelectorAll("[data-cashflow-component]").forEach((button) => {
    const isActive = state.cashflowComponents[button.dataset.cashflowComponent] !== false;
    button.classList.toggle("is-muted", !isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });
  document.querySelector("[data-cashflow-zoom='out']").disabled = state.cashflowZoom <= 1;
  document.querySelector("[data-cashflow-zoom='in']").disabled = state.cashflowZoom >= 4;
  document.getElementById("cashflowChartTitle").textContent =
    `${state.overviewCashflowCumulative ? "Cumulative " : ""}Compensation Cashflow`;
  const componentLabels = visibleCashflowComponents(state).map((component) => component.label.toLowerCase()).join(", ");
  document.getElementById("cashflowChartSubtitle").textContent =
    state.overviewCashflowCumulative
      ? `Running ${state.overviewCashflowView} totals for ${componentLabels}.`
      : state.overviewCashflowView === "annual"
      ? `Stacked annual totals for ${componentLabels}.`
      : `Stacked monthly payouts for ${componentLabels}.`;
  document.getElementById("cashflowDetailTitle").textContent =
    `${state.detailCashflowCumulative ? "Cumulative " : ""}${state.detailCashflowView === "annual" ? "Annual Detail" : "Monthly Detail"}`;
  document.getElementById("cashflowDetailSubtitle").textContent =
    state.detailCashflowView === "annual"
      ? "Each projection year in the selected horizon."
      : "Each month in the selected projection horizon.";

  renderSummary(state, model);
  renderCashflowChart(state, DEFAULTS, model);
  renderEquityChart(state, model);
  renderMix(state, model);
  renderTables(state, DEFAULTS, model);
  renderEquityStats(state, model);
  renderScenarios(state, DEFAULTS);

  const mixPeriodSelect = document.getElementById("mixPeriodSelect");
  mixPeriodSelect.addEventListener("change", (event) => {
    state.mixPeriod = event.target.value;
    saveState();
    render();
  });
  setActiveTab(activeTab);
}

document.getElementById("scenarioName").addEventListener("input", (event) => {
  state.scenarioName = event.target.value;
  saveState();
});

document.querySelectorAll("[data-tab]").forEach((button) => {
  button.addEventListener("click", () => setActiveTab(button.dataset.tab));
});

document.querySelectorAll("[data-overview-cashflow-view]").forEach((button) => {
  button.addEventListener("click", () => {
    state.overviewCashflowView = button.dataset.overviewCashflowView;
    resetCashflowWindow(state, cashflowDisplayRows(state, DEFAULTS, projectionFor(state, DEFAULTS), state.overviewCashflowView).length);
    saveState();
    render();
  });
});

document.querySelectorAll("[data-detail-cashflow-view]").forEach((button) => {
  button.addEventListener("click", () => {
    state.detailCashflowView = button.dataset.detailCashflowView;
    saveState();
    render();
  });
});

document.querySelector("[data-overview-cumulative]").addEventListener("click", () => {
  state.overviewCashflowCumulative = !state.overviewCashflowCumulative;
  saveState();
  render();
});

document.querySelector("[data-detail-cumulative]").addEventListener("click", () => {
  state.detailCashflowCumulative = !state.detailCashflowCumulative;
  saveState();
  render();
});

document.querySelectorAll("[data-cashflow-component]").forEach((button) => {
  button.addEventListener("click", () => {
    const key = button.dataset.cashflowComponent;
    const isActive = state.cashflowComponents[key] !== false;
    const activeCount = cashflowComponentMeta.filter((component) => state.cashflowComponents[component.key] !== false).length;
    if (isActive && activeCount === 1) return;
    state.cashflowComponents[key] = !isActive;
    saveState();
    render();
  });
});

document.querySelectorAll("[data-cashflow-zoom]").forEach((button) => {
  button.addEventListener("click", () => {
    const model = projectionFor(state, DEFAULTS);
    const rows = cashflowDisplayRows(state, DEFAULTS, model, state.overviewCashflowView);
    resizeCashflowWindow(state, button.dataset.cashflowZoom, rows.length);
    saveState();
    render();
  });
});

document.querySelector("[data-cashflow-zoom-reset]").addEventListener("click", () => {
  const model = projectionFor(state, DEFAULTS);
  const rows = cashflowDisplayRows(state, DEFAULTS, model, state.overviewCashflowView);
  resetCashflowWindow(state, rows.length);
  saveState();
  render();
});

function chartPointerRatio(chart, event) {
  const svg = chart.querySelector("svg");
  const chartRect = chart.getBoundingClientRect();
  const svgWidth = svg?.getBoundingClientRect().width || chart.clientWidth || 1;
  const pointerX = event.clientX - chartRect.left + chart.scrollLeft;
  return Math.min(1, Math.max(0, pointerX / svgWidth));
}

function installRectangleZoom(chart, totalRowsForChart, selectWindowByRatios) {
  chart.addEventListener("mousedown", (event) => {
    if (event.button !== 0 || event.target.closest("button, input, select")) return;
    event.preventDefault();
    const startRatio = chartPointerRatio(chart, event);
    const startClientX = event.clientX;
    const chartRect = chart.getBoundingClientRect();
    const overlay = document.createElement("div");
    overlay.className = "zoom-selection";
    chart.appendChild(overlay);

    const updateOverlay = (clientX) => {
      const start = Math.min(startClientX, clientX);
      const end = Math.max(startClientX, clientX);
      const left = Math.max(0, Math.min(chart.clientWidth, start - chartRect.left));
      const right = Math.max(0, Math.min(chart.clientWidth, end - chartRect.left));
      overlay.style.left = `${left}px`;
      overlay.style.width = `${Math.max(2, right - left)}px`;
    };

    updateOverlay(startClientX);
    const onMove = (moveEvent) => {
      updateOverlay(moveEvent.clientX);
    };
    const onUp = (upEvent) => {
      document.removeEventListener("mousemove", onMove);
      document.removeEventListener("mouseup", onUp);
      overlay.remove();
      if (Math.abs(upEvent.clientX - startClientX) < 8) return;
      selectWindowByRatios(totalRowsForChart(), startRatio, chartPointerRatio(chart, upEvent));
      saveState();
      render();
    };
    document.addEventListener("mousemove", onMove);
    document.addEventListener("mouseup", onUp);
  });
}

installRectangleZoom(
  document.getElementById("cashflowChart"),
  () => cashflowDisplayRows(state, DEFAULTS, projectionFor(state, DEFAULTS), state.overviewCashflowView).length,
  (total, startRatio, endRatio) => selectCashflowWindowByRatios(state, total, startRatio, endRatio),
);

document.getElementById("cashflowChart").addEventListener(
  "wheel",
  (event) => {
    event.preventDefault();
    const chart = event.currentTarget;
    const anchorRatio = chartPointerRatio(chart, event);
    const model = projectionFor(state, DEFAULTS);
    const rows = cashflowDisplayRows(state, DEFAULTS, model, state.overviewCashflowView);
    resizeCashflowWindow(state, event.deltaY > 0 ? "out" : "in", rows.length, anchorRatio);
    saveState();
    render();
  },
  { passive: false },
);

document.getElementById("cashflowChart").addEventListener("keydown", (event) => {
  const keyMap = {
    "+": "in",
    "=": "in",
    "-": "out",
    _: "out",
  };
  const direction = keyMap[event.key];
  if (!direction) return;
  const model = projectionFor(state, DEFAULTS);
  const rows = cashflowDisplayRows(state, DEFAULTS, model, state.overviewCashflowView);
  resizeCashflowWindow(state, direction, rows.length);
  saveState();
  render();
});

document.querySelectorAll("[data-equity-zoom]").forEach((button) => {
  button.addEventListener("click", () => {
    const model = projectionFor(state, DEFAULTS);
    resizeEquityWindow(state, button.dataset.equityZoom, model.rows.length);
    saveState();
    render();
  });
});

document.querySelector("[data-equity-zoom-reset]").addEventListener("click", () => {
  const model = projectionFor(state, DEFAULTS);
  resetEquityWindow(state, model.rows.length);
  saveState();
  render();
});

installRectangleZoom(
  document.getElementById("equityChart"),
  () => projectionFor(state, DEFAULTS).rows.length,
  (total, startRatio, endRatio) => selectEquityWindowByRatios(state, total, startRatio, endRatio),
);

document.getElementById("equityChart").addEventListener(
  "wheel",
  (event) => {
    event.preventDefault();
    const chart = event.currentTarget;
    const anchorRatio = chartPointerRatio(chart, event);
    const model = projectionFor(state, DEFAULTS);
    resizeEquityWindow(state, event.deltaY > 0 ? "out" : "in", model.rows.length, anchorRatio);
    saveState();
    render();
  },
  { passive: false },
);

document.getElementById("equityChart").addEventListener("keydown", (event) => {
  const keyMap = {
    "+": "in",
    "=": "in",
    "-": "out",
    _: "out",
  };
  const direction = keyMap[event.key];
  if (!direction) return;
  const model = projectionFor(state, DEFAULTS);
  resizeEquityWindow(state, direction, model.rows.length);
  saveState();
  render();
});

document.getElementById("equityChart").addEventListener("click", (event) => {
  const point = event.target.closest("[data-equity-index]");
  if (!point) return;
  state.selectedEquityPoint = point.dataset.equityIndex;
  saveState();
  renderEquityPointDetail(state, projectionFor(state, DEFAULTS));
});

document.getElementById("equityChart").addEventListener("mouseover", (event) => {
  const point = event.target.closest("[data-equity-index]");
  if (!point) return;
  renderEquityPointDetail(state, projectionFor(state, DEFAULTS), point.dataset.equityIndex);
});

document.getElementById("cashflowWindowStart").addEventListener("input", (event) => {
  const total = Math.max(1, asNumber(event.target.max, 0) + 1);
  state.cashflowWindowStart = Math.round(asNumber(event.target.value, 0));
  const window = normalizedCashflowWindow(state, total);
  if (window.end <= window.start) {
    state.cashflowWindowEnd = Math.min(total, window.start + 1);
  }
  saveState();
  render();
});

document.getElementById("cashflowWindowEnd").addEventListener("input", (event) => {
  const total = Math.max(1, asNumber(event.target.max, 1));
  state.cashflowWindowEnd = Math.round(asNumber(event.target.value, total));
  const window = normalizedCashflowWindow(state, total);
  if (window.start >= window.end) {
    state.cashflowWindowStart = Math.max(0, window.end - 1);
  }
  saveState();
  render();
});

document.getElementById("equityWindowStart").addEventListener("input", (event) => {
  const total = Math.max(1, asNumber(event.target.max, 0) + 1);
  state.equityWindowStart = Math.round(asNumber(event.target.value, 0));
  const window = normalizedEquityWindow(state, total);
  if (window.end <= window.start) {
    state.equityWindowEnd = Math.min(total, window.start + 1);
  }
  saveState();
  render();
});

document.getElementById("equityWindowEnd").addEventListener("input", (event) => {
  const total = Math.max(1, asNumber(event.target.max, 1));
  state.equityWindowEnd = Math.round(asNumber(event.target.value, total));
  const window = normalizedEquityWindow(state, total);
  if (window.start >= window.end) {
    state.equityWindowStart = Math.max(0, window.end - 1);
  }
  saveState();
  render();
});

document.getElementById("resetButton").addEventListener("click", () => {
  Object.assign(state, { ...DEFAULTS, cashflowComponents: { ...DEFAULTS.cashflowComponents } });
  saveState();
  renderControls();
  render();
});

document.getElementById("exportButton").addEventListener("click", () => exportCsv(state, DEFAULTS));
document.getElementById("exportReportButton").addEventListener("click", () => exportHtmlReport(state, DEFAULTS));

renderControls();
render();

})();
